package com.example.nikhil.stickyclock.utils;

/**
 * Created by Nikhil on 25-Sep-16.
 */
public interface Constants {

    String SHARED_PREF_COUNTRIES = "SHARED_PREF_COUNTRIES";
    String SHARED_PREF_TIMEZONES = "SHARED_PREF_TIMEZONES";
    String SHARED_PREF_TUTORIAL_DONE = "SHARED_PREF_TUTORIAL_DONE";
    String SHARED_PREF_ICON_NEEDED = "SHARED_PREF_ICON_NEEDED";
    String SHARED_PREF_FIRST_SCREEN = "SHARED_PREF_FIRST_SCREEN";
    String SHARED_PREF_SECOND_SCREEN = "SHARED_PREF_SECOND_SCREEN";

}

